#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 5

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define NO_AUTO_SHIFT_TAB
#define NO_AUTO_SHIFT_ALPHA
#define SERIAL_NUMBER "mEaYP/bvrN7Q"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 1

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

